development:
  adapter: async
  adapter: solid_cable
  polling_interval: 5.seconds

test:
  adapter: test

production:
  adapter: solid_cable
  channel_prefix: quest_log_production
  polling_interval: 1.0
