development:
  adapter: async
  adapter: solid_cable
  polling_interval: 5.seconds

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: quest_log_production
  adapter: solid_cable
  ssl_params: { verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> }
  polling_interval: 1.0.seconds
